### ISSUE TITLE
example_report path broken

### ISSUE THREAD

**Issue by BryanDonovan** [bahmutov/js-complexity-viz#1]
Hi, in this line in js-complexity-viz.js:

```
    filename = path.resolve(path.dirname(process.argv[1]), "test\\example_report.html");
```

.. the path does not work on most developer systems (i.e., unix-based).

The solution is simple though... use path.join():

```
  filename = path.resolve(path.dirname(process.argv[1]), path.join("test", "example_report.html"));
```

**Comment by ssoper** [comment]
+1

**Comment by ssoper** [comment]
Also I believe that should be `var htmlFilename = …` in the fix above since `filename` is already coming in as an argument (ver 0.2.3)

**Comment by bahmutov** [comment]
test\ problem fixed (using path.join)
i have not switched example_report.html yet
