### ISSUE TITLE
OSX Install

### ISSUE THREAD

**Issue by mattimatti** [bahmutov/js-complexity-viz#2]
Hi, 

i've installed the tool on OSX 10.7

``` javascript
sudo npm install -g js-complexity-viz
```

but running 

``` javascript
js-complexity-viz -h
```

rises this error

``` javascript
env: node\r: No such file or directory
```

How to get it working?

Thank you in advance!

**Comment by weisjohn** [comment]
@mattimatti it's a line-endings problem. If you don't have `dos2unix` installed, you need to `brew install dos2unix`
Then, you need to convert the file, such as.  

```
$ cd `which js-complexity-viz`/..
$ dos2unix js-complexity-viz.js 
dos2unix: converting file js-complexity-viz.js to Unix format ...
```

Once that's done, you should be good.

```
$ js-complexity-viz 
Visualize JS files complexity.
Usage: js-complexity-viz
[...]
```

@bahmutov please see https://github.com/stubbornella/csslint/issues/82 for the same issue and how they fixed it there...
